services:

  bankmore-transferencia-api:
    container_name: bankmore-transferencia-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:80
      - 8083:443
    environment:
      ASPNETCORE_ENVIRONMENT: Docker